<?php

/**
 * @file
 * Contains vertical_timeline.module..
 */

use Drupal\views\ViewExecutable;
use Drupal\Component\Datetime\DateTimePlus;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function vertical_timeline_theme_suggestions_views_view_alter(&$suggestions, &$vars, $hook) {
  // Look only for views that use the Vertical Timeline style plugin.
  if (!empty($vars['view']) && $vars['view']->style_plugin instanceof \Drupal\vertical_timeline\Plugin\views\style\VerticalTimelineStyle) {
    // Tell the theme system to use a different template instead of the default views_view template.
    // This template adds markup outside of the area the style plugin can control.
    $suggestions[] = 'vertical_timeline__vertical_timeline';
  }
}

/**
 * Implements hook_registry_alter().
 *
 * Update the theme registry with our theme suggestion. This would not be required
 * if the template was provided by the theme, but is needed so a module can provide
 * a template.
 */
function vertical_timeline_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'vertical_timeline');
  // Duplicate the registry entry for the views_view template.
  $theme_registry['vertical_timeline__vertical_timeline'] = $theme_registry['views_view'];
  // Update the entry to indicate that the template is in the module directory, not the theme directory.
  $theme_registry['vertical_timeline__vertical_timeline']['template'] = 'vertical-timeline--vertical-timeline';
  $theme_registry['vertical_timeline__vertical_timeline']['path'] = $path . '/templates';
}
